"""
Auto-generated by strategy_improver.py — best backtested parameters.
This variant hard-codes the optimised parameter set so profile defaults
(such as global target_r) cannot override them.
"""
from __future__ import annotations
from tradebot_sci.strategy.variants.forex_structure_breakout import ForexStructureBreakout


class ForexStructureBreakoutBest(ForexStructureBreakout):
    """Parameter-optimised structure-breakout variant."""

    SESSION_PROFILE = ["forex_structure_breakout_best:london_open", "forex_structure_breakout_best:us_open"]

    def __init__(self, **kwargs):
        # Optimised values always win; incoming kwargs are only used for
        # non-optimised parameters (e.g. name, profile_settings).
        merged = dict(kwargs)
        merged.update({
    "target_r": 2.0,
    "breakout_lookback": 4,
    "adx_min": 22.0,
    "volume_min_ratio": 1.7,
    "stop_floor_pct": 0.0012,
    "score_threshold": 60.0
})
        super().__init__(**merged)
